<?php

/**
 * Form callback for payment forms.
 *
 * This callback has to be set in the payment controller class. This function
 * assumes that a PaymentMethodController using this callback implements the
 * paymentForm() method according to @see FormCallbacksMixin.
 */
function payment_forms_payment_form(array &$element, array &$form_state) {
  $payment = $form_state['payment'];
  $form = $payment->method->controller->paymentForm($payment);
  $element = $form->form($element, $form_state, $payment);
  $element['#form'] = $form;
  return $element;
}

/**
 * Callback for form validation.
 *
 * The function name is automatically derived from the
 * form callback name.
 */
function payment_forms_payment_form_validate(&$element, &$form_state) {
  $payment = $form_state['payment'];
  $form = $element['#form'];
  $form->validate($element, $form_state, $payment);
}

/**
 * Helper functions that recursively merges $defaults into a $config array.
 */
function _payment_forms_merge_array_defaults(&$config, $defaults) {
  $config += $defaults;
  foreach ($config as $key => $value) {
    if (is_array($value) && isset($defaults[$key]) && is_array($defaults[$key])) {
      $is_assoc = empty($value) || array_keys($value) !== range(0, count($value) - 1);
      if ($is_assoc) {
        _payment_forms_merge_array_defaults($config[$key], $defaults[$key]);
      }
    }
  }
}

/**
 * Form element callback: Payment method configuration.
 *
 * The callback to this function has to be set in the payment controller class.
 * This function assumes that a the PaymentMethodController class implements the
 * configurationForm() method according to @see FormCallbacksMixin.
 */
function payment_forms_method_configuration_form($element, &$form_state) {
  $method = $form_state['payment_method'];
  _payment_forms_merge_array_defaults($method->controller_data, $method->controller->controller_data_defaults);
  $form = $method->controller->configurationForm($method);
  $element = $form->form($element, $form_state, $method);
  $element['#form'] = $form;
  return $element;
}

/**
 * Form validate callback for the payment_method configuration.
 *
 * @see payment_forms_method_configuration_form().
 */
function payment_forms_method_configuration_form_validate($element, &$form_state) {
  $method = $form_state['payment_method'];
  $form = $element['#form'];
  $form->validate($element, $form_state, $method);
}
